language: node_js
node_js:
  - "6"

install:
  - npm install

script:
  - node_modules/.bin/nyc --reporter=lcov --reporter=text-lcov npm test --coverage

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
